### ISSUE TITLE
The "Hashtag Regular Expression" setting does not work

### ISSUE THREAD

**Issue by giobifo** [justoverclockl/flarum-ext-hashtag#10]
Hi, I tried to use this extension but if i set the: "**Hashtag Regular Expression**", this doesn't work.

To fix the problem I got to line 656 (for me) of this file: `forumapp\public\assets\forum.js` and i found this string:
`var regex = new RegExp('' + flarum_forum_app__WEBPACK_IMPORTED_MODULE_0___default.a.forum.attribute('justoverclock-hashtag.regex'), 'gu');`

I solved the problem by replace the previous line with this: `var regex = new RegExp('' + flarum_forum_app__WEBPACK_IMPORTED_MODULE_0___default.a.forum.attribute('justoverclock-hashtag.regex'), 'g');`

I simply replaced `gu` with `g`

I hope it will be useful

**Comment by zerosonesfun** [comment]
The u is part of the original regular expression though. I don’t see why that would cause an issue. The u adds Unicode support which you need so that it works for all languages. 

A more likely reason is that something was cached. Or, the post or settings just needed to be re-saved. 

I have noticed that sometimes after updating or reinstalling this extension I have to re-edit a post to get things to start working again. I don’t know what that’s about.

**Comment by zerosonesfun** [comment]
Quick update: I tested this again. I can confirm that you must save the settings once for the extension to work. You don’t have to input anything, just click save.

**Comment by justoverclockl** [comment]
Yes I need to debug this tomorrow or today later
